### ISSUE TITLE
Auto Answer Error

### ISSUE THREAD

**Issue by Cromiad** [KEN-2000l/EducationPerfected#10]
Hi Guys,
Firstly, thank you for making this amazing tool for EP, I've been using it ever since you re updated the code to do the clipboard auto answer, and I love it! But one problem I've had all the time using the auto answer, I keep getting this:
![image](https://user-images.githubusercontent.com/92068310/136308809-85b9fc44-c2ae-45aa-8489-939a6b380b4c.png)

I'm not even doing German, and it randomly kills my answer streak because of this. 
It would be awesome if you could fix this, because then your script would be flawless.

Kind Regards,
Cromiad 🙂

**Comment by garv-shah** [comment]
Until we find a solution to that, I'm pretty sure that if you turn down the timing a tiny bit then it will have enough time to load the answer. 
@KEN-2000l As a possible solution, if it's possible to detect if the answer is loaded yet or not, we could add an async await section somewhere in the code. Theoretically, this shouldn't make the script much slower and will just equate for the user's wifi connection?

**Comment by KEN-2000l** [comment]
It looks like the problem isn't the question not loading, but rather sometimes education perfect simply does not register the answer we are trying to input. I have debugging log statements which demonstrates this behavior...
You slow down the correct answer submission delay to see that ep says the submitted answer is blank

**Comment by Cromiad** [comment]
Uhh, there is 190 lines of code, which line do I change????

**Comment by garv-shah** [comment]
oh whoops i forgot, ken changed it so you can't manually set ur time interval, I'll hopefully create a website thing where you can change ur settings.
sorry about that :P
