### ISSUE TITLE
script+ issues

### ISSUE THREAD

**Issue by garv-shah** [KEN-2000l/EducationPerfected#12]
# Bug
The new script doesn't really seem to work for me. Instead, every single time it actually works, it gives me the error from here: https://github.com/KEN-2000l/EducationPerfected/issues/10

The algorithm for automatically going through pages seems to work, but ends up giving the error above. A lot of the time, it doesn't even manage to do the tasks. For example, if I'm on a task starter page that it should be able to complete, a lot of the time it just logs "Completed one task." to the console and does nothing else.

# Enhancement
Also, macOS support doesn't work at all, but that's expected and I can fix that later. Also, later once I have the website for settings working, we can merge both the scripts into one and then have it as a mode on the settings page. Just a suggestion for when I'm not lazy :P
So I can create the website in a place where you can manage it, would you be able to turn the repo into a GitHub Pages site?

**Comment by suryasingh1** [comment]
Is there any way to make it wait 1 to 2 seconds at every question it would make it much less sus for ep

**Comment by garv-shah** [comment]
yup, just use the script from this comment [here](https://github.com/KEN-2000l/EducationPerfected/issues/16#issuecomment-962854874)
It prompts you at the start, in milliseconds, so if you want a 1 second delay, you'd just type in 1000, and it won't be as sus

**Comment by suryasingh1** [comment]
Is there any way to make it wait 1 to 2 seconds on each question to make it less sus for ep

**Comment by suryasingh1** [comment]
Sorry for commenting again it was a lag

**Comment by garv-shah** [comment]
all g

**Comment by suryasingh1** [comment]
Thanks that is goated. You are a legend

**Comment by suryasingh1** [comment]
Is there any way to do the same on script+.js as well because this one gets a lot of answers wrong even if you do alt+r

**Comment by garv-shah** [comment]
i'm not sure, since ken's mostly worked on script+
i doubt that script+ will make it more accurate though, since iirc they work on the same algorithm
@KEN-2000l any chance you could drop an edited version of script+ with a delay?

**Comment by garv-shah** [comment]
also next time, probably open a new issue, since the delay's pretty unrelated to the script+ issues

**Comment by KEN-2000l** [comment]
> i'm not sure, since ken's mostly worked on script+ i doubt that script+ will make it more accurate though, since iirc they work on the same algorithm @KEN-2000l any chance you could drop an edited version of script+ with a delay?

um script+ is a pile of idk that is device/platform-dependent and I only made it to afk some points
even script.js has few issues and im just really lazy
so basically many times it is more than the answer delay

**Comment by suryasingh1** [comment]
The auto answer is not working

The semi auto is but auto answer is not. Did ep change something?

**Comment by suryasingh1** [comment]
The auto run script has just stopped is there a way to get it going again. I think ep has just tweaked little display or button variable setting and stuff. Cause the semi auto works but the auto isn’t working at all it does nothing

**Comment by suryasingh1** [comment]
Is there a way you can fix it also sorry about posting the issue in the wrong area

**Comment by suryasingh1** [comment]
My theory was right they have changed they names or something because the console returns could not find had button. Also sorry for all these comments I am really stressed for some reason.

**Comment by suryasingh1** [comment]
Never mind it was a trap

If you change tweak the scrip to work. It notifies ep that you have been using hacks.

**Comment by garv-shah** [comment]
wait actually, how do you know it notified them?

**Comment by garv-shah** [comment]
> The auto run script has just stopped is there a way to get it going again. I think ep has just tweaked little display or button variable setting and stuff. Cause the semi auto works but the auto isn’t working at all it does nothing

is this the auto answer for script+ or just normal script? normal script seems to be working fine for me

**Comment by suryasingh1** [comment]
It’s the normal script and a pop came up saying using scripts is inapopriate and that the ep team will be notified

**Comment by suryasingh1** [comment]
It might be to check if I personally was cheating. Who knows?

**Comment by suryasingh1** [comment]
For me when I do inspect the button comes up as button#submit-button.ng-binding.ng-scope

**Comment by garv-shah** [comment]
yeah that was an issue created from before as well, they don't know, they just put that there as a safeguard to discourage users from doing so. also yeah, try to make new issues please, don't just stick to this one, it makes organisation hard.

I'll check the name changes in a bit

**Comment by suryasingh1** [comment]
If you mean ‘[Not really an issue but this is funny] EP thinks I don't know what I'm doing’ that’s not what happened after tweaking the code it literally kicked me out of the task to homepage and it said that using console whatever bad and ep team will be notified

**Comment by garv-shah** [comment]
oh wait crap, actually?!?
damn, is there any way u can provide a recording of that, I'll try and find a way to make the script not do that

**Comment by suryasingh1** [comment]
I tried using macros and everything they are literally detecting for digital ways of the button being clicked. And as soon as it happens they go nope this guy cheated. 

Here is a image

[](url
![Uploading IMG_1847.jpeg…]()
)

**Comment by garv-shah** [comment]
i think you clicked "comment" before it actually uploaded, would you be able to send it again?

**Comment by suryasingh1** [comment]
![IMG_1847](https://user-images.githubusercontent.com/97711555/162845723-db53efdd-bd33-43f4-bc6e-bef1063c4a3b.jpeg)

**Comment by garv-shah** [comment]
OMG that's crazy that they've implemented that, damn
imma try and fix that rn one sec

**Comment by KEN-2000l** [comment]
okay it removed `button#explanation-button` when answering which was the only way we could get the script to trigger submission (by calling `.click()`)

the normal `button#submit-button` whose `.click()` didn't use to do anything now "notifies security team"

**Comment by suryasingh1** [comment]
Wait does that mean you can fix it? Also I built a physical robot that uses the same technique as your code but in real life. As in it uses a camera got track the question its pretty cool. It can type scroll whatever. Basically there is no way ep can find out now. Because it will work normally

**Comment by KEN-2000l** [comment]
not sure if I can fix using Javascript that runs on the website level
but if I use like python selenium it would work completely fine but just a lot slower (compared to previous speeds)

a physical robot sounds really cool and really hard to do at the same time 😂

**Comment by suryasingh1** [comment]
I kinda made my dad do it. I didnt do crap

**Comment by suryasingh1** [comment]
Ok I can finally say I actually contributed to this project in the slightest and not just ask for help. But basically if you use Autohotkey.com and create a hotkey with it which pastes clipboard and presses enter on keyboard. Ep doesn’t detect it. So you would run semi auto and this hotkey together and it works fine. Create a hotkey loop and there you go

**Comment by garv-shah** [comment]
yeah that's what i used to do on my old script lmao, but ideally there'd be a faster way for the enters to be on the correct time so it's faster

```javascript
function callClickEvent(element){
    var evt = document.createEvent("HTMLEvents"); 
    evt.initEvent("click", true, true); 
    element.dispatchEvent(evt);
}

function callClickEvent2(element){
    var evt = document.createEvent("MouseEvents");
    evt.initMouseEvent("click", true, true, window,
    0, 0, 0, 0, 0, false, false, false, false, 0, null);
    element.dispatchEvent(evt);
}

callClickEvent(document.getElementById("myElement"))
callClickEvent2(document.getElementById("myElement"))
```

I think these javascript functions would work as well to simulate a human click, so we don't have to move the whole codebase

**Comment by KEN-2000l** [comment]
events like that don't work and still triggers their anticheat

**Comment by Susmaster64** [comment]
they actually made an anti-cheat?
Good job EP I guess. Does this mean we have to go back to the stone ages and use python OCRs to detect the text in the image and compare it to the word list?

**Comment by Susmaster64** [comment]
and to get around the button click problem can't you just make js simulate a enter press or make it call on an external script?

**Comment by KEN-2000l** [comment]
check the v2 folder 
i fixed it
can't simulate a real press with a script running in the context of the website
so I used a standalone script with puppeteer to control a browser

**Comment by KEN-2000l** [comment]
imma close this because i will (s∞n™) rewrite script+ in a similar way to how I fixed the normal script
and that approach should solve the existing issues here with better control over the browser
plus many things in here are kinda off topic

**Comment by HelloBello234** [comment]
<img width="715" alt="Screenshot 2022-10-27 212322" src="https://user-images.githubusercontent.com/110455010/198260818-afc5f98c-455c-4ddf-b782-393f3bf5163e.png">
Can someone help me with this!

**Comment by HelloBello234** [comment]
https://pastebin.pl/view/fdb858db

Thats the full error
