### ISSUE TITLE
Some Answers Returning Undefined

### ISSUE THREAD

**Issue by garv-shah** [KEN-2000l/EducationPerfected#2]
some answers return undefined, i don't really know why yet but i can try and figure it out eventually (most likely due to the way the strings are split)

**Comment by KEN-2000l** [comment]
Thanks... I have actually also looked into this and many times it is just that some words in the list and the words in the questions are actually different. Blame EP for this.
You can however make it so it remembers the correct answer from the incorrect-prompt but I am lazy as always xD

**Comment by garv-shah** [comment]
oh yeah sounds good i might add that to my fork if i can be bothered :)

**Comment by garv-shah** [comment]
actually i found a way to fix it without manually remembering the correct answer. Turns out the mergeLists function was only considering semi-colons and not commas. If you just add in the second split for the string everything works fine (though the remembering method could act as a good failsafe in the future). I implemented it into my fork, so if you want you can just merge the two from my pull request :D

**Comment by KEN-2000l** [comment]
makes sense
