### ISSUE TITLE
 Non fully automatic version does not run from folders

### ISSUE THREAD

**Issue by Susmaster64** [KEN-2000l/EducationPerfected#23]
Enhancement?

**Comment by garv-shah** [comment]
what would you mean by does not run from folders? are you running script+ or the normal script?

**Comment by Susmaster64** [comment]
script. It does not run from folders/ directories like said at bottom of readme

**Comment by garv-shah** [comment]
that's not a thing for script, that's the whole point of script+
<img width="866" alt="Screen Shot 2022-02-19 at 8 31 37 am" src="https://user-images.githubusercontent.com/64292655/154763997-dcb77d11-22bf-4d78-a434-69a2b6742d78.png">
This whole section only applies to script+, the point of it being "better" is that it can self navigate and work from folders and stuff like that. So yeah, the normal script doesn't work from folders, it's not intended to, that feature is script+ specific, but script+ is extremely unstable, and rn it doesn't work for anyone besides ken (including me)
