### ISSUE TITLE
ALT + S Not Doing Anything Script+

### ISSUE THREAD

**Issue by lkeld** [KEN-2000l/EducationPerfected#25]

**Comment by lkeld** [comment]
I accidentally hit enter whilst attempting to make a new line. 

I have added the script in through console and have also tried with tampermonkey but to no avail. If i could get a fix that would be greatly appreciated.

**Comment by garv-shah** [comment]
this is a known issue https://github.com/KEN-2000l/EducationPerfected/issues/12
currently, script+ doesn't work at all, don't use it :)
