### ISSUE TITLE
[Not really an issue but this is funny] EP thinks I don't know what I'm doing

### ISSUE THREAD

**Issue by Susmaster64** [KEN-2000l/EducationPerfected#27]
![image](https://user-images.githubusercontent.com/99788724/161212758-706766ab-caa0-416c-88d9-f417acf50688.png)
I use de-googled chromium as my daily browser (on my laptop) and use this script and LOL look education perfect is stereotyping against people that use developer browsers.

P.S. on the education perfect tournament rules, apparently there is a "robust" cheating detection system meanwhile I'm doing 300 questions a minute and not getting caught.

**Comment by garv-shah** [comment]
oh damn wow, that wasn't there last time, i guess there must be a ton of people using bots sgdhajg
yeah, EP's anti-cheat system is kind of bad, like the program doesn't even do anything "wrong" or get information from where it's not supposed to, it just gets the answers EP already gives u
honestly, it'd be interesting if they actually cracked down on bots like this and improved their "robust" systems to make the platform better

also, just a question, do u think it'd be better to have the program in the form it's in now, or have a chrome/safari/firefox extension with a UI and settings?

**Comment by Susmaster64** [comment]
UI would be a big quality of life improvement but personally i don't need it. It would make kiddos use this easier but personally no.

**Comment by Susmaster64** [comment]
OK NVM its not just chromiuim it says that on Firefox, chrome, opera and Microsoft edge.  Maybe it caught up with the fact that I'm cheating O_O. Im going to go check the trigger for that

**Comment by garv-shah** [comment]
nah, i think it's a thing they added for all users recently, pretty sure there isn't a trigger, there's probably been an influx of people using bots and they're catching on

**Comment by garv-shah** [comment]
> UI would be a big quality of life improvement but personally i don't need it. It would make kiddos use this easier but personally no.

thanks thanks
