### ISSUE TITLE
Reads comma as seperation in answer

### ISSUE THREAD

**Issue by tomb56** [KEN-2000l/EducationPerfected#31]
The answer is sopesed to be "No, I cannot do it at all." but instead it just does "No".

**Comment by garv-shah** [comment]
that's an issue with it splitting by commas, with the fully automatic version it should learn from its mistakes
there isn't really a way to get it to work without splitting by commas or semi-colons, so questions with either of those two characters can be inaccurate

**Comment by tomb56** [comment]
but when i run fully automatic it flags my account and reports suspisious activity

**Comment by garv-shah** [comment]
ken created version 2 for that, so try using that and see how it goes, if not u might just have to manually enter that one

**Comment by tomb56** [comment]
is there a way i can edit the code to make it wait half a second or a second before submiting the answer

**Comment by KEN-2000l** [comment]
First, add this function somewhere within the file:
```js
    function sleep(ms) {
        return new Promise(resolve => setTimeout(resolve, ms));
    }
```

then add one line in `answerLoop()` (here is the entire function, the new line is near the bottom):

```js
    // main function that continually answers questions until completion modal pops up or hotkey pressed again
    async function answerLoop() {
        if (TOGGLE) throw Error("Tried to initiate answerLoop while it is already running");

        TOGGLE = true;
        console.log("answerLoop entered.");

        while (TOGGLE) {
            let question = await page.$eval(DIR.question_css, el => el.textContent);
            let answer = findAnswer(question);

            await page.click(DIR.answer_box_css, {clickCount: 3});
            page.keyboard.sendCharacter(answer);
            page.keyboard.press('Enter');

            // special case: modal pops up
            if (await page.$(DIR.modal_css)) {
                // incorrect answer and modal pops up; initiate answer-correction procedure
                if (await page.$(DIR.modal_question_css) !== null) {
                    await correctAnswer(question, answer);
                    await deleteModals();
                // list complete; clicks button to exit
                } else if (await page.$(DIR.exit_button_css)) {
                    await page.click(DIR.exit_button_css);
                    break;
                } else if (await page.$(DIR.exit_continue_button_css)) {
                    await page.click(DIR.exit_continue_button_css);
                    break;
                } else {
                    // no idea what the modal is for so let's just pretend it doesn't exist
                    await deleteModals();
                }
            }
            // ADD THIS LINE
            await sleep(500);
            // ADD THIS LINE
        }

        await deleteModals();
        console.log('answerLoop Exited.');
    }
```

**Comment by KEN-2000l** [comment]
500 is 500 milliseconds of waiting time; adjust as necessary

**Comment by tomb56** [comment]
thanks but i can;t work out how to install v2
i went into cmd but dont where the files that i have to run are anythin
![5788979](https://user-images.githubusercontent.com/98370757/168170951-d36fa8de-f116-4a49-82f8-0c7820a5b1e4.jpg)
g

**Comment by garv-shah** [comment]
so yeah, puppeteer is installed, but you have cd into the directory with the js file you downloaded and run it from there. You do seem to be on windows though, so you should just be able to run the start.cmd file

**Comment by tomb56** [comment]
how do i download the file it just opens the code for it but wont download

**Comment by tomb56** [comment]
worked it out

**Comment by tomb56** [comment]
can i just add the same sleep command to v2 as i did to v1

**Comment by garv-shah** [comment]
the above is for v2, you can find sleep scripts for v1 in the closed issues

**Comment by tomb56** [comment]
Thank you sooo much

**Comment by garv-shah** [comment]
:D
