### ISSUE TITLE
key strokes don't work

### ISSUE THREAD

**Issue by garv-shah** [KEN-2000l/EducationPerfected#32]
i'm not too sure why this is, it might be another macos thing, but i'll do some additional testing and try and fix it later
basically none of the keystrokes are detected, so the hotkeys don't work either

**Comment by garv-shah** [comment]
it might be better to simulate an enter keypress on the v1 script instead for ease of use, I'll try that tomorrow

**Comment by KEN-2000l** [comment]
I have no idea why it doesn't work for you/macos
I simple injected a eventListener into the site which triggers Puppeteer functions

but so far it has worked on multiple windows systems (me and other ppls')

and scripts running in the context of the page cannot replicate real human actions (a security limitation) and EP does check for this (as part of their anticheat).
you can still try in case I missed something but I don't think it would work (and even if it did, it is possible for EP to fix), so I went straight with puppeteer

**Comment by garv-shah** [comment]
yeah, that makes sense, I hope there's a way to have it as easy to use as the previous script but also with elevated privileges

**Comment by garv-shah** [comment]
the issue seems to be with SSO, whenever you log in through your school, puppeteer stops being able to detect any keystrokes, which is probably a security measure by microsoft to prevent password logging
it probably works fine with email and password logins in EP, but my account doesn't offer that, so that was probably the issue
I'll try and find a way to log keystrokes after the login process has finished

**Comment by garv-shah** [comment]
fixed with https://github.com/KEN-2000l/EducationPerfected/commit/3256bd96a3371fd37d87213a2d41d2991b7615eb
basically it just waits until the starting page loads to inject the js

**Comment by KEN-2000l** [comment]
it does work with email and password as I assumed everyone used that

but if SSO causes some navigation or pop-up then the Injected event listeners will be cleared and break, which makes sense :D
