### ISSUE TITLE
auto answer bug maybe

### ISSUE THREAD

**Issue by AQUAT1CS** [KEN-2000l/EducationPerfected#5]
when activating auto answer it doesn't seem to actually answer the questions, it only pastes the answer then instantly deletes it. Everything else works fine though, great script.

**Comment by garv-shah** [comment]
Would you be able to send a link to what activity you are doing as well as the browser version?

**Comment by garv-shah** [comment]
@AQUAT1CS Can you try again with the latest version?

**Comment by KEN-2000l** [comment]
Closing it because should be fixed and no response
