### ISSUE TITLE
Semi-Automatic Inconsistencies 

### ISSUE THREAD

**Issue by garv-shah** [KEN-2000l/EducationPerfected#7]
On any browser, if you start semi-automatic, then switch to fully-automatic and then go back to semi-automatic, the behaviour is a bit buggy. No clue why, but it seems to trail back a question and not update the clipboard in time

**Comment by KEN-2000l** [comment]
I didn't notice anything special... The solution does update a bit slow sometimes (which idk why; the interval is 10 times per second)

**Comment by garv-shah** [comment]
hmm odd

**Comment by garv-shah** [comment]
Ah nvm I found out why. Basically, the fully-automatic mode was setting the loopInterval, which the semi-automatic mode also relies on. I was setting it to 1000 milliseconds, so it updated a bit slow. Simple fix: just reset the loop interval every time you turn off fully-automatic!
https://github.com/KEN-2000l/EducationPerfected/commit/cd303bb3a6869456bef24425d7aa5d22a0839411
